# Generated by Django 4.2 on 2023-05-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_hed', models.CharField(max_length=60)),
                ('ser_data', models.TextField(max_length=200)),
                ('ser_img', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
            ],
        ),
    ]
